version: '3.1'
services:
    gcc:
        image: gcc:latest
        container_name: gcc
        command: /bin/bash
        volumes:
            - /mnt/c/Users/ldejuan/work/aaData/home:/root
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/inputdir:/outputdir
            - /mnt/c/Users/ldejuan/work/aaDATA/home/data/strategies/trading/marketdata:/inputdir
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '100m'
    analysis:
        image: analysis:0.1
        container_name: analysis
        command: /bin/bash
        volumes: 
            - /mnt/c/Users/ldejuan/work/aaData/home:/root
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/inputdir:/inputdir
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/outputdir:/outputdir

    jupyter:
        image: analysis:0.1
        container_name: jupyter
        command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/root --no-browser
        volumes: 
            - /mnt/c/Users/ldejuan/work/aaData/home/strategies/analysis:/root
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/nputdir:/inputdir
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/outputdir:/outputdir
        ports:
            - 8888:8888
            
    onemacd:
        image: onemacd:0.1
        container_name: onemacd
        command: /onemacd
        volumes:
            - /mnt/c/Users/ldejuan/work/aaData/home/data/strategies/analysis/inputdir:/outputdir
            - /mnt/c/Users/ldejuan/work/aaDATA/home/data/strategies/trading/marketdata:/inputdir
