version: '3.1'
services:
    gcc:
        image: gcc:latest
        container_name: gcc
        command: /bin/bash
        volumes:
            - /mnt/c/Users/ldejuan/work/aaData/home:/root
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '100m'
    analysis:
        image: analysis:0.1
        container_name: analysis
        command: /bin/bash
        volumes: 
            - /mnt/c/Users/ldejuan/work/aaData/home:/root
            - /mnt/c/Users/ldejuan/work/aaData/home/data/analysis/inputdir:/inputdir
            - /mnt/c/Users/ldejuan/work/aaData/home/data/analysis/outputdir:/outputdir
